### ISSUE TITLE
rabellamy/nginx:0.1.0 not found :/

### ISSUE THREAD

**Issue by pablorsk** [scottrigby/NGINX-PHP-7-K8S-Deployment#3]
```
Failed to pull image "rabellamy/nginx:0.1.0": rpc error: code = 2 desc = Error: image rabellamy/nginx:0.1.0 not found
Error syncing pod
```

**Comment by HerpaMoTeH** [comment]
To fix this simply edit 'resources/kubernetes/deployments/local-deployment.yaml' to have the following content:
```yaml
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: php7-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: php7
    spec:
      containers:
      - name: php7
        image: r6by/php7:0.1.1
        ports:
        - containerPort: 9000
        volumeMounts:
          - mountPath: /var/www/html
            name: src
      volumes:
      - name: src
        hostPath:
          path:

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8088
```
